import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { GridSmallBackgroundDemo } from "@/components/ui/bg";
import { ClerkProvider } from "@clerk/nextjs";
import Header from "./components/Header";
import Footer from "./components/Footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider signInForceRedirectUrl={"/"}>
      <html lang="en">
        <body className={inter.className}>
          <GridSmallBackgroundDemo />
          <div className="relative z-10">
            <Header />
            {children}
            <Footer />
          </div>
        </body>
      </html>
    </ClerkProvider>
  );
}
